### ISSUE TITLE
File is created for whatever command line option flag is given.

### ISSUE THREAD

**Issue by andylytical** [access-ci-org/ipf#16]
When this line is executed,

https://github.com/access-ci-org/ipf/blob/9cbf94e3c4f9447fe76f60f18db1157534343b89/ipf/etc/ipf/init.d/ipf-WORKFLOW#L52

a new file named `-d` is created in the local directory.

**Comment by andylytical** [comment]
I have traced it down to this line:

https://github.com/access-ci-org/ipf/blob/9cbf94e3c4f9447fe76f60f18db1157534343b89/ipf/catalog.py#L24

but not sure where to go from there.

**Comment by andylytical** [comment]
Following the install from repo method (defined in https://github.com/access-ci-org/ipf/blob/CTT-304/aloftus/backwards_compatable/QUICKSTART.md), I have validated that whatever command line flag I pass will create a file by that name. For example, if I pass the long option name `--daemon` instead of the short option name, the file created will be named `--daemon`. I have even passed an invalid command line option such as `-k` and a file will be created with that name.

**Comment by ericblau** [comment]
I believe I have solved this with the commit in the github-issue-16 branch.

The issue is that pre_populate_position.py (which is a convenience script for setting up the workflow where IPF monitors the SLURM slumctl log) was being imported as a module when catalog.py was doing "import ipf" to use pkgutil to walk the modules that IPF provides.  However, python will run the module when imported, so pre_populate_position.py was being run.  The solution was to put pre_populate_position's code inside a "def main():" and add a "if __name__ == '__main__':
 main()" so that the code is not run when imported, only when invoked as a script.  

See https://stackoverflow.com/questions/6523791/why-is-python-running-my-module-when-i-import-it-and-how-do-i-stop-it

**Comment by andylytical** [comment]
@ericblau Can this issue be closed?

**Comment by ericblau** [comment]
Yep, this issue is complete.
